---
name: PHP Composer + PHPUnit + PHPStan

on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'

  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'

permissions:
  contents: read

jobs:
  # Note: https://docs.github.com/en/actions/using-workflows/reusing-workflows The strategy property is not supported in any job that calls a reusable workflow.
  call-workflow:
    uses: WorkOfStan/seablast-actions/.github/workflows/php-composer-dependencies-reusable.yml@main
    with:
      # JSON
      php-version: '["5.3", "5.4", "5.5", "5.6", "7.0", "7.1", "7.2", "7.3", "7.4"]'
      # TODO: add , "8.0", "8.1", "8.2", "8.3" when 5.x removed
