---
name: PHP syntax

on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'
  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    # Limit the running time
    timeout-minutes: 10
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
        php-version: ["5.3", "5.4", "5.5", "5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP ${{ matrix.php-version }} Test on ${{ runner.os }}"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          # coverage none turns off Xdebug as in PHP 5.6,7.0 it would change (format) var_dump output
          coverage: none
  
      - name: "PHP syntax"
        run: |
          #for file in ./src/*.php; do
          #  php -l "$file"
          #done
          find ./ -name "*.php" | xargs -n 1 php -l
  
